weight = 1
languageCode = "pt-br"
languageName = "Português"
hasCJKLanguage = false
copyright = "Este trabalho está licenciado sob uma Licença Creative Commons Atribuição-NãoComercial 4.0 Internacional."